blog/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entrada-lista',
    ), 
    path(
        'entrada/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entrada-detalle',
    ), 
     
]

blog/applications/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageView.as_view(),
        name='perfil',
    ), 
    path(
        'add-entrada/<pk>', 
        views.AddFavoritesView.as_view(),
        name='add-favorito',
    ), 
    path(
        'delete-entrada/<pk>', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favorito',
    ), 
       
]

blog/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='home',
    ), 
    path(
        'register-suscription', 
        views.SuscriberCreateView.as_view(),
        name='add-suscription',
    ), 
    path(
        'contact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ),   
]

blog/applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.entrada.urls')),
    path('', include('applications.favoritos.urls')),

    #urls para ckeditor
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" method="POST" action="{% url 'home_app:add-contact' %}">{% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombres
                    <input type="text" placeholder="nombres..." name="full_name" id="id_full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="text" placeholder="Correo ..." name="email" id="id_email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje" name="messagge" id="id_messagge"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="summit" class="success button">Enviar</button>
                </div>
            </div>
        </form>
        <!--Aqui utilizamos los processors-->
        <p class="cell large-8">Otras formas de Contacto:</p>
        <p class="cell large-8">
          <span class="label warning">{{email}}</span>
          <span class="label warning">{{phone}}</span>
        </p>

    </div>
</div>

blog/templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="{% url 'home_app:home' %}" style="font-size: 20px; color: #0277bd;">
                Neunapp Blog
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="{% url 'home_app:home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'entrada_app:entrada-lista' %}">Blog</a>
                </li>
                <li>
                    
                    {% if not user.is_anonymous %}
                        <a href="{% url 'favoritos_app:perfil' %}" class="warning button">Perfil</a>
                    {% else %}  
                        <a href="{% url 'users_app:user-login' %}" class="success button">Acceder</a>
                    
                    {% endif %}
                        
                    
                </li>
                
            </ul>
        </div>
    </div>
</header>