blog/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entrada-lista',
    ), 
    path(
        'entrada/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entrada-detalle',
    ), 
     
]

blog/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='home',
    ), 
    path(
        'register-suscription', 
        views.SuscriberCreateView.as_view(),
        name='add-suscription',
    ), 
    path(
        'contact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ),   
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.entrada.urls')),
    path('', include('applications.favoritos.urls')),

    #urls para ckeditor
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/applications/home/models.py
from django.db import models
from django.db.models.fields import EmailField
#esto nos trae el campo de created y modified, se le instala con el pip install django-model-utils
from model_utils.models import TimeStampedModel

# Create your models here.

class Home(TimeStampedModel):
    title = models.CharField('Titulo', max_length=30)
    description = models.TextField()
    about_title = models.CharField('Titulo Nosotros', max_length=50)
    about_text = models.TextField()
    contact_email = models.EmailField('Email de Contacto',blank=True, null=True)
    phone = models.CharField('Telefono de contacto', max_length=20)

    class Meta:
        verbose_name = 'Pagina Principal'
        verbose_name_plural ='Pagina Principal'

    def __str__(self):
        return self.title


class Suscribers(TimeStampedModel):
    email = models.EmailField()

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

    def __str__(self):
        return self.email


class Contact(TimeStampedModel):
    full_name =models.CharField('Nombres', max_length=60)
    email = models.EmailField()
    messagge = models.TextField()

    class Meta:
        verbose_name='Contacto'
        verbose_name_plural ='Mensajes'

    def __str__(self):
        return self.full_name

blog/applications/home/forms.py
from django import forms
from .models import Contact, Suscribers


class SuscribersForm(forms.ModelForm):
    class Meta:
        model = Suscribers
        fields = {
            'email',
        }
        widgets ={
            'email': forms.EmailInput(
                attrs={
                    'placeholder': "Correo Electronico ...",
                }
            )
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('__all__')
        

blog/applications/home/views.py
import datetime
#
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from applications.entrada.models import Entry
from .models import Home
from .forms import ContactForm, SuscribersForm





from django.views.generic import (
    TemplateView,
    CreateView
)



class HomePageView(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        #cargamos el home
        context['home'] = Home.objects.latest('created')
        #contexto de portada
        context['portada'] = Entry.objects.entrada_portada()
        #contexto para los articulos del home
        context['entrada_home'] = Entry.objects.entrada_home()
        #contexto para las entradas recientes
        context['entrada_reciente'] = Entry.objects.entrada_reciente()
        #enviamos formulario de suscripcion
        context['suscripcion']  = SuscribersForm
        return context


class SuscriberCreateView(CreateView):
    form_class = SuscribersForm
    success_url = '.'


class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '.'

blog/templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{ portada.image.url }}" style="height: 278px;">
                <div class="card-section">
                  <h4><a href="{% url 'entrada_app:entrada-detalle' portada.id %}">{{portada.title}}</a></h4>
                  <p>{{portada.resume}}</p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">

            
            {% for entrada in entrada_home %}
                <div class="cell small-12 large-6">
                    <div class="card" style="width: 100%;">
                        <img src="{{entrada.image.url}}" style="height: 120px;">
                        <div class="card-section">
                        <h5><a href="{% url 'entrada_app:entrada-detalle' entrada.id %}">{{entrada.title | truncatechars:40}}</a></h5>
                        </div>
                    </div>
                </div>
                
            {% endfor %}
                
            
           
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h5>{{home.about_title}}:</h5>
            <p>
                {{home.about_text}}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <!-- Con el action le decimos que url queremos que ejecute-->
                <form class="grid-x grid-margin-x" method="POST" action="{% url 'home_app:add-suscription' %}">{% csrf_token %}
                    <div class="cell small-12">
                        {{suscripcion.email}}
                    </div>
                    <div class="cell small-12">
                        <button type="summit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Articulos Recientes:</h3>
        
        {% for entrada in entrada_reciente %}
            
            <div class="cell small-6 large-4">
                <div class="card" style="width: 100%;">
                    <img src="{{entrada.image.url}}" style="height: 200px;">
                    <div class="card-section">
                    <h4><a href="{% url 'entrada_app:entrada-detalle' entrada.id %}">{{entrada.title | truncatechars:40}}</a></h4>
                    <p>{{entrada.resume | truncatechars:60}}</p>
                    </div>
                </div>
            </div>
            
        {% endfor %}
            
        
        
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}