blog/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entrada-lista',
    ), 
    path(
        'entrada/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entrada-detalle',
    ), 
     
]

blog/applications/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageView.as_view(),
        name='perfil',
    ), 
    path(
        'add-entrada/<pk>', 
        views.AddFavoritesView.as_view(),
        name='add-favorito',
    ), 
    path(
        'delete-entrada/<pk>', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favorito',
    ), 
       
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.entrada.urls')),
    path('', include('applications.favoritos.urls')),

    #urls para ckeditor
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/applications/entrada/models.py
from enum import unique
from django.db import models
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings

from .managers import EntradaManager



class Category(TimeStampedModel):
    short_name = models.CharField('Nombre Corto', max_length=15, unique=True)
    name = models.CharField('Nombre', max_length=50)

    class Meta:
        verbose_name='Categoria'
        verbose_name_plural = 'Categorias'


    def __str__(self):
        return self.name


class Tag(TimeStampedModel):
    name = models.CharField('Nombre', max_length=30)

    class Meta:
        verbose_name='Etiqueta'
        verbose_name_plural = 'Etiquetas'


    def __str__(self):
        return self.name




class Entry(TimeStampedModel):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models. ManyToManyField(Tag)
    title = models.CharField('Titulo', max_length=30)
    resume = models.TextField('Resumen')
    content = RichTextUploadingField('Contenido')
    public = models.BooleanField(default=False)
    image = models.ImageField('Imagen', upload_to='media/')
    portada = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    slug= models.SlugField(editable=False, max_length=300)


    objects = EntradaManager()

    class Meta:
        verbose_name='Entrada'
        verbose_name_plural = 'Entradas'


    def __str__(self):
        return self.title

blog/applications/entrada/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Entry, Category
# Create your views here.


class EntryListView(ListView):
    
    template_name = "entrada/lista.html"
    context_object_name = "entradas"
    paginate_by = 3

    
    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categorias'] = Category.objects.all()
        return context
    

    def get_queryset(self) :
        kword = self.request.GET.get("kword", '')
        categoria = self.request.GET.get("categoria", '')
        #busqueda
        resultado = Entry.objects.buscar_entrada(kword, categoria)
        return resultado



class EntryDetailView(DetailView):
    model = Entry
    template_name = "entrada/detail.html"

blog/templates/entrada/base_entrada.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/entrada/detail.html
{% extends "entrada/base_entrada.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <h3 class="cell">{{object.title}}</h3>

        <!-- bloque de contenido del articulo -->
        <div class="cell large-8">
            <div class="cell callout primary">
                <h5>Resumen:</h5>
                <p>{{entry.resume}}</p>
            </div>
            <div>
                <!-- se les llama templatetags "safe"-->
                <p>{{entry.content | safe}}</p>
                
            </div>
        </div>
        <!-- FIN bloque contenido del articulo -->


        <!-- bloque llamada a la accion -->
        <div class="cell large-4">
            <div class="card" style="width: 100%;">
                <img src="{{entry.image.url}}">
                <div class="card-section" style="width: 100%;">
                    <form class="blog-action" action="{% url 'favoritos_app:add-favorito' entry.id %}" method="post">{% csrf_token %}
                    
                        
                        <button type="summit" class="button alert">Agregar a Favoritos</button>
                  
                    </form>
                </div>
            </div>
        </div>
        <!-- FIN bloque llamada a la accion -->

    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

blog/templates/entrada/lista.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- primer bloque pantalla blog -->
        <div class="cell small-12 large-8">

            <!-- bloque de buscador -->
            <form class="input-group" method="GET">{% csrf_token %}
                <input class="input-group-field" type="text" id="kword" name="kword" placeholder="Buscar ...">
                <div class="input-group-button">
                  <input type="submit" class="button" value="Buscar">
                </div>
            </form>
            <!-- FIN bloque de formulario -->

            <!-- inicio bloque de resultados de busqueda -->
            <div class="grid-x grid-margin-x">
                
                {% for entrada in entradas %}
                    <div class="cell small-6 large-4">
                        <div class="card" style="width: 100%;">
                            <img src="{{entrada.image.url}}" style="height: 250px;">
                            <div class="card-section">
                            <h4><a href="{% url 'entrada_app:entrada-detalle' entrada.id %}">{{entrada.title | truncatechars:15}}</a></h4>
                            <p>{{entrada.resume | truncatechars:30}}</p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                <h3 style="color: red;">No hay resultados</h3>
                {% endfor %}
                    
                
            </div>
            <!-- FIN bloque de resultados de busqueda -->

        </div>
        <!-- FIN primer bloque pantalla blog -->


        <!-- inicio del segundo bloque - categorias -->
        <div class="cell small-12 large-4" style="height: 500px;">
            <h4>Categorias</h4>
            <ul class="vertical menu">
                
                {% for categoria in categorias  %}
                <li><a href="?categoria={{ categoria.short_name }}">{{categoria.name}}</a></li>
                    
                {% endfor %}
                <li><a href="?categoria=">Todos</a></li>
                    
                
            </ul>
        </div>
        <!-- FIN inicio del segundo bloque - categorias -->
    
    </div>

    <!-- inicio de bloque de paginacion -->
    <div class="cell">
            
        {% if is_paginated %}

        <nav aria-label="Pagination">
            <ul class="pagination">
            
            {% if page_obj.has_previous %}
            <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                
            {% endif %}
                   
            
            {% for pagina in paginator.page_range %}

            
            {% ifequal pagina page_obj.number  %} 
            <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
            
            {% else %} 
            <li><a href="?page={{pagina}}">{{ pagina }}</a></li>   
            {% endifequal %}
                   
            {% endfor %}
                
            
            
            {% if page_obj.has_next %}
            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Next</a></li>
            {% endif %}
            </ul>
        </nav>
            
        {% endif %}
            
        
    </div>
    <!-- FIN bloque de paginacion -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}