blog/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entrada-lista',
    ), 
    path(
        'entrada/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entrada-detalle',
    ), 
     
]

blog/applications/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageView.as_view(),
        name='perfil',
    ), 
    path(
        'add-entrada/<pk>', 
        views.AddFavoritesView.as_view(),
        name='add-favorito',
    ), 
    path(
        'delete-entrada/<pk>', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favorito',
    ), 
       
]

blog/applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.entrada.urls')),
    path('', include('applications.favoritos.urls')),

    #urls para ckeditor
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/applications/favoritos/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from django.conf import settings
from applications.entrada.models import Entry
from .managers import FavoritesManagaer
# Create your models here.


class Favorites(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_favorites' ,on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry,   related_name='entry_favorites' ,on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'entry')
        verbose_name ='Entrada Favorita'
        verbose_name_plural = 'Entradas Favoritas'

    objects=FavoritesManagaer()

    def __str__(self):
        return self.entry.title

blog/applications/favoritos/views.py
from django.contrib.auth import login
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse, reverse_lazy

from django.views.generic import ListView, View, DeleteView

from .models import Favorites
from applications.entrada.models import Entry


class UserPageView(LoginRequiredMixin,ListView):
    
    template_name = "favoritos/perfil.html"
    context_object_name='favoritos'
    login_url = reverse_lazy('users_app:login')


    def get_queryset(self):
        return Favorites.objects.favorito_user(self.request.user)

class AddFavoritesView(LoginRequiredMixin,View):
    login_url = reverse_lazy('users_app:user-login')
    def post(self,request, *args, **kwargs):
        usuario = self.request.user
        entrada = Entry.objects.get(id=self.kwargs['pk'])

        Favorites.objects.create(
            user=usuario,
            entry=entrada,

        )

        return HttpResponseRedirect(
            reverse(
                'favoritos_app:perfil'
            )
        )



class FavoritesDeleteView(DeleteView):
    model = Favorites
    success_url = reverse_lazy('favoritos_app:perfil')
    

blog/templates/favoritos/base_favorito.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/favoritos/perfil.html
<!-- head para PC -->
{% extends "favoritos/base_favorito.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h5>{{user.full_name}}</h5>
                <p>{{user.email}} - {{user.ocupation}} - {{user.date_birth}}</p>
                <a href="#">Editar Datos</a>
                <p><a href="{% url 'users_app:user-logout' %}" class="clear button secondary">Salir</a></p>
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->


        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">

            
            {% for favorito in favoritos %}
            <div class="cell small-12">
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{favorito.entry.image.url}}">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{favorito.entry.title}}</h3>
                        <p class="card-favoritos-body-text">{{favorito.entry.resume}}</p>
                        <form class="card-favoritos-body-actions" method="POST" action="{% url 'favoritos_app:delete-favorito' favorito.id  %}">{% csrf_token %}
                            <a class="button warning" href="{% url 'entrada_app:entrada-detalle' favorito.entry.id %}">Ver</a>
                            <button class="button alert" type="summit">Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
                
            {% endfor %}
                
            
            
        </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}